### ISSUE TITLE
Disappearing favourites?

### ISSUE THREAD

**Issue by MiniMoose12** [dulleh/akhyou#21]
I love the app but my favourites keep disappearing :( I think you store them serverside and my school blocks that server but not the anime sources... Please make them stored locally or something. Its really annoying and makes bookmarking on chrome better than using the app.......

**Comment by dulleh** [comment]
There is no server side! :D It's all stored locally so it must be a bug. :/ Are you on the latest build - when did you last update?

_The Disappearance of MiniMoose's Favorites_

**Comment by MiniMoose12** [comment]
I just installed the app a few days ago. I just updated my phones rom. So I started fresh again. Could it be because I dont properly close the app? I dont like keeping stuff open and often close then with the recents menu. Woukd that effect it at all? Also this was happening on my old rom just the same... i dont think its the roms fault because It doesnt havI any issue with the other apps on my phone.

Im running a note 5 ported rom called sixperience on my n910c note 4. No xposed or anything special.

**Comment by MiniMoose12** [comment]
Turns out there was an error message on the bottom of the screen. I think ad away could be of fault? Here is the error from a screenshot. http://i.imgur.com/eWta6Xg.jpg

Looks something like: attempt to invoke virtual method ' void

**Comment by dulleh** [comment]
Hmm, the way you close the app shouldn't be a problem but I'll investigate that. Ad away probably isn't what's causing it since favourites don't make any network requests past the regular browsing ones. You could try disabling it for Akhyou but I doubt it would cause much of a difference.

>http://i.imgur.com/eWta6Xg.jpg

I thought I had fixed that error ;-; I might just have to rewrite how favourites are saved... again.

Thanks for the reports, they're much appreciated. I'll get to the bottom of this. :+1:
